### ISSUE TITLE
Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request 

### ISSUE THREAD

**Issue by lostsnow** [aliyun/alibabacloud-gdb-tools#21]
```
Traceback (most recent call last):
  File "GdbDataRemover.py", line 125, in <module>
    main()
  File "GdbDataRemover.py", line 122, in main
    gdb_data_remover.drop(args.label, args.drop_edge_only)
  File "GdbDataRemover.py", line 48, in drop
    self.__drop_all(True)
  File "GdbDataRemover.py", line 64, in __drop_all
    self.__generic_batch_drop(cnt_dsl, cnt_params,
  File "GdbDataRemover.py", line 97, in __generic_batch_drop
    curr_dropped_cnt = curr_drop_result.one()[0]
  File "/usr/local/lib/python3.8/dist-packages/gremlin_python/driver/resultset.py", line 83, in one
    return self.done.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gremlin_python/driver/connection.py", line 80, in _receive
    status_code = self._protocol.data_received(data, self._results)
  File "/usr/local/lib/python3.8/dist-packages/gremlin_python/driver/protocol.py", line 97, in data_received
    return self.data_received(data, results_dict)
  File "/usr/local/lib/python3.8/dist-packages/gremlin_python/driver/protocol.py", line 110, in data_received
    raise GremlinServerError(message["status"])
gremlin_python.driver.protocol.GremlinServerError: 598: Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.E().limit(limit).sideEffect(drop()).count()]
```

**Comment by sandszhouSZ** [comment]
fixed
